CREATE TABLE IF NOT EXISTS todos (
                                         id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                                         task VARCHAR NOT NULL,
                                         added TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                         due TIMESTAMP DEFAULT null,
                                         done BOOLEAN DEFAULT false
);
