create table if not exists todos (
                                         id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                                         task VARCHAR NOT NULL,
                                        added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
